server:
  port: 8096
spring:
  application:
    name: microservice-provider-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                           # 指定数据源
    platform: h2                        # 指定数据源类型
    schema: classpath:schema.sql        # 指定h2数据库的建表脚本
    data: classpath:data.sql            # 指定h2数据库的数据脚本
logging:                                # 配置日志级别，让hibernate打印出执行的SQL
  file: user3.log
  level:
    root: WARN
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.101.69.135:8761/eureka/
  instance:
    prefer-ip-address: true